<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <parent>
        <artifactId>north</artifactId>
        <groupId>org.alter.north</groupId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>

    <name>North Engine Core</name>
    <description>A North game engine core</description>

    <artifactId>core</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <slf4j.version>2.0.7</slf4j.version>
        <logback.version>1.4.7</logback.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-assimp</artifactId>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-glfw</artifactId>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-openal</artifactId>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-opengl</artifactId>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-stb</artifactId>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl</artifactId>
            <classifier>${lwjgl.natives}</classifier>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-assimp</artifactId>
            <classifier>${lwjgl.natives}</classifier>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-glfw</artifactId>
            <classifier>${lwjgl.natives}</classifier>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-openal</artifactId>
            <classifier>${lwjgl.natives}</classifier>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-opengl</artifactId>
            <classifier>${lwjgl.natives}</classifier>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-stb</artifactId>
            <classifier>${lwjgl.natives}</classifier>
        </dependency>
        <dependency>
            <groupId>org.joml</groupId>
            <artifactId>joml</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback.version}</version>
        </dependency>
    </dependencies>

    <build>
        <filters>
            <filter>src/main/resources/north.properties</filter>
        </filters>
        <resources>
            <resource>
                <directory>${basedir}/src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <!-- Плагин для создания JAR с Class-Path в манифесте -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <classpathPrefix>lib/</classpathPrefix>
                            <mainClass>org.north.core.MainThread</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>

            <!-- Плагин для копирования зависимостей в lib/ -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/lib</outputDirectory>
                            <overWriteReleases>false</overWriteReleases>
                            <overWriteSnapshots>false</overWriteSnapshots>
                            <overWriteIfNewer>true</overWriteIfNewer>
                            <includeScope>runtime</includeScope>
                            <excludeArtifactIds>
                                lwjgl-natives-windows,lwjgl-natives-linux,lwjgl-natives-macos,
                                lwjgl-assimp-natives-windows,lwjgl-assimp-natives-linux,lwjgl-assimp-natives-macos,
                                lwjgl-glfw-natives-windows,lwjgl-glfw-natives-linux,lwjgl-glfw-natives-macos,
                                lwjgl-openal-natives-windows,lwjgl-openal-natives-linux,lwjgl-openal-natives-macos,
                                lwjgl-opengl-natives-windows,lwjgl-opengl-natives-linux,lwjgl-opengl-natives-macos,
                                lwjgl-stb-natives-windows,lwjgl-stb-natives-linux,lwjgl-stb-natives-macos
                            </excludeArtifactIds>
                        </configuration>
                    </execution>

                    <!-- Отдельное копирование нативных библиотек -->
                    <execution>
                        <id>copy-native-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/natives</outputDirectory>
                            <overWriteReleases>false</overWriteReleases>
                            <overWriteSnapshots>false</overWriteSnapshots>
                            <overWriteIfNewer>true</overWriteIfNewer>
                            <includeArtifactIds>
                                lwjgl-natives-windows,lwjgl-natives-linux,lwjgl-natives-macos,
                                lwjgl-assimp-natives-windows,lwjgl-assimp-natives-linux,lwjgl-assimp-natives-macos,
                                lwjgl-glfw-natives-windows,lwjgl-glfw-natives-linux,lwjgl-glfw-natives-macos,
                                lwjgl-openal-natives-windows,lwjgl-openal-natives-linux,lwjgl-openal-natives-macos,
                                lwjgl-opengl-natives-windows,lwjgl-opengl-natives-linux,lwjgl-opengl-natives-macos,
                                lwjgl-stb-natives-windows,lwjgl-stb-natives-linux,lwjgl-stb-natives-macos
                            </includeArtifactIds>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- Компилятор -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
