#info
application.version=0.0.001

#application run settings
application.window.title=test_view
application.window.width=512
application.window.height=512
application.window.vsync=false

#scene/world config
scene.storage.max-entity-count=1_000_000
scene.storage.max-component-per-entity-count=16

#editor
application.editor.enabled=false
application.editor.camera.intermediate-state-on-focus-loss=true
application.editor.process.update.smooth-stop-and-start=true

system.package=org/north/core/system
process.package=org/north/core/system/process

#logger
logger.severity=INFO
