#info
application.version=0.0.001

#editor
application.editor.enabled=false
application.editor.camera.intermediate-state-on-focus-loss=false

system.package=org/north/core/system
process.package=org/north/core/system/process

#logger
logger.severity=INFO
